const columns = [
  {name: "ID", uid: "id"},
  {name: "DATE", uid: "date"},
  {name: "CUTTING No.", uid: "cuttingNo", sortable: true},
  {name: "STYLE", uid: "styleName"},
  {name: "DESIGN", uid: "designName"},
  {name: "DETAILS", uid: "details"},
  {name: "QUANTITY (Pcs)", uid: "quantityPcs", sortable: true},
  {name: "CUT RATE", uid: "cuttingRate", sortable: true},
  {name: "TOTAL CUT RATE", uid: "total", sortable: true},
  {name: "FABRICS WEIGHT", uid: "fabricsWeight", sortable: true},
  {name: "FABRICS RATE", uid: "fabricsRate", sortable: true},
  {name: "FABRICS COST PER (Pcs)", uid: "fabricsCostPerPcs", sortable: true},
  {name: "TOTAL COST PER UNIT", uid: "totalCostPerUnit", sortable: true},
  {name: "STATUS", uid: "status"},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Complete", uid: "complete"},
];

const users = [
  {
    id: 1,
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    quantityPcs: "504",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
    cuttingRate: "3.0",
    fabricsWeight: "76.90",
    fabricsRate: "900",
  },
  {
    id: 2,
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    quantityPcs: "510",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
    cuttingRate: "3.0",
    fabricsWeight: "77.20",
    fabricsRate: "900",
  },
  {
    id: 3,
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
    cuttingRate: "4.0",
    fabricsWeight: "75.30",
    fabricsRate: "900",
  },
  {
    id: 4,
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    quantityPcs: "504",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
    cuttingRate: "3.0",
    fabricsWeight: "76.90",
    fabricsRate: "900",
  },
  {
    id: 5,
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    quantityPcs: "510",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
    cuttingRate: "3.0",
    fabricsWeight: "77.20",
    fabricsRate: "900",
  },
  {
    id: 6,
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
    cuttingRate: "4.0",
    fabricsWeight: "75.30",
    fabricsRate: "900",
  },
  {
    id: 7,
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
    cuttingRate: "4.0",
    fabricsWeight: "75.30",
    fabricsRate: "900",
  },
  {
    id: 8,
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
    cuttingRate: "4.0",
    fabricsWeight: "75.30",
    fabricsRate: "900",
  },
  {
    id: 9,
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
    cuttingRate: "4.0",
    fabricsWeight: "75.30",
    fabricsRate: "900",
  },
  {
    id: 10,
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
    cuttingRate: "4.0",
    fabricsWeight: "75.30",
    fabricsRate: "900",
  },
];

export {columns, users, statusOptions};
