const columns = [
  {name: "ID", uid: "id"},
  {name: "DATE", uid: "date"},
  {name: "STYLE", uid: "styleName"},
  {name: "DESIGN", uid: "designName"},
  {name: "DETAILS", uid: "details"},
  {name: "DESCRIPTION", uid: "description"},
  {name: "QUANTITY", uid: "totalQuantityPcs", sortable: true},
  {name: "TOTAL REJECT", uid: "totalReject", sortable: true},
  {name: "RATE", uid: "rate", sortable: true},
  {name: "TOTAL", uid: "total", sortable: true},
  {name: "TOTAL COST PER PCS", uid: "totalCostPerPcs", sortable: true},
  {name: "STATUS", uid: "status"},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Complete", uid: "complete"},
];

const users = [
  {
    id: 1,
    rate: "12.0",
    totalReject: "2",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    description: "--",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
    totalQuantityPcs: "492",
  },
  {
    id: 2,
    rate: "20.0",
    totalReject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    description: "--",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
    totalQuantityPcs: "510",
  },
  {
    id: 3,
    rate: "12.0",
    totalReject: "2",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    description: "--",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
    totalQuantityPcs: "492",
  },
  {
    id: 4,
    rate: "20.0",
    totalReject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    description: "--",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
    totalQuantityPcs: "510",
  },
  {
    id: 5,
    rate: "12.0",
    totalReject: "2",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    description: "--",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
    totalQuantityPcs: "492",
  },
  {
    id: 6,
    rate: "20.0",
    totalReject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    description: "--",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
    totalQuantityPcs: "510",
  },
  {
    id: 7,
    rate: "12.0",
    totalReject: "2",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    description: "--",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
    totalQuantityPcs: "492",
  },
  {
    id: 8,
    rate: "20.0",
    totalReject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    description: "--",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
    totalQuantityPcs: "510",
  }
];

export {columns, users, statusOptions};
