const columns = [
  {name: "ID", uid: "id"},
  {name: "DATE", uid: "date"},
  {name: "CUT No.", uid: "cuttingNo", sortable: true},
  {name: "STYLE", uid: "styleName"},
  {name: "DESIGN", uid: "designName"},
  {name: "DETAILS", uid: "details"},
  {name: "DESCRIPTION", uid: "desceiption"},
  {name: "QUANTITY", uid: "quantityPcs", sortable: true},
  {name: "REJECT", uid: "reject", sortable: true},
  {name: "RATE", uid: "rate", sortable: true},
  {name: "TOTAL", uid: "total", sortable: true},
  {name: "STATUS", uid: "status"},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Complete", uid: "complete"},
];

const users = [
  {
    id: 1,
    rate: "50",
    reject: "10",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    quantityPcs: "494",
    desceiption: "10k",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
  },
  {
    id: 2,
    rate: "30",
    reject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    quantityPcs: "510",
    desceiption: "2k",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
  },
  {
    id: 3,
    rate: "6",
    reject: "10",
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    desceiption: "6k",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
  },
  {
    id: 4,
    rate: "50",
    reject: "10",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    quantityPcs: "494",
    desceiption: "10k",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
  },
  {
    id: 5,
    rate: "30",
    reject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    quantityPcs: "510",
    desceiption: "2k",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
  },
  {
    id: 6,
    rate: "6",
    reject: "10",
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    desceiption: "6k",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
  },
  {
    id: 7,
    rate: "50",
    reject: "10",
    date: "FEB-18",
    cuttingNo: "66",
    status: "active",
    quantityPcs: "494",
    desceiption: "10k",
    details: "Marsrize",
    designName: "J.G Embo",
    styleName: "Polo Shirt",
  },
  {
    id: 8,
    rate: "30",
    reject: "10",
    date: "FEB-19",
    cuttingNo: "67",
    status: "paused",
    quantityPcs: "510",
    desceiption: "2k",
    details: "Polister Slab",
    designName: "Saittu Sticker",
    styleName: "T-Shirt",
  },
  {
    id: 9,
    rate: "6",
    reject: "10",
    date: "FEB-20",
    cuttingNo: "68",
    status: "complete",
    quantityPcs: "498",
    desceiption: "6k",
    details: "Dalai",
    designName: "Jacket Neck",
    styleName: "Joggers",
  },
];

export {columns, users, statusOptions};
